Меняет имя наставника в readme
htmlacademy-javascript/1938675-kekstagram-29 pull request #1
Opened 2023-06-07 15:43 UTC by yartseva-ksenia

2023-06-07 15:51 UTC, baileys-li requested changes

2023-06-07 15:51 UTC, baileys-li commented on Readme.md
> +* Наставник: `Arthur Litovko`.
Давай я тоже буду ссылкой
```suggestion
* Наставник: [Arthur Litovko](https://github.com/baileys-li).
```

2023-06-07 16:29 UTC, yartseva-ksenia commented on Readme.md
> +* Наставник: `Arthur Litovko`.
Изменила readme, закоммитила и запушила, но почему-то в пулреквесте не вижу коммита

2023-06-07 16:39 UTC, merged

2023-06-08 20:18 UTC, baileys-li commented on Readme.md
> +* Наставник: `Arthur Litovko`.
Так он снизу