Нужно больше функций
htmlacademy-javascript/1938675-kekstagram-29 pull request #2
Opened 2023-06-14 09:46 UTC by yartseva-ksenia

2023-06-15 08:38 UTC, baileys-li requested changes

2023-06-15 08:38 UTC, baileys-li commented on js/functions.js
> +console.log('Ожидаю 2023 — получаю ' + getNumber('2023 год'));
Сейчас падает, потому что функция закоментирована

2023-06-15 08:38 UTC, baileys-li commented on js/functions.js
> +    const NumberIsNan===true ? number += string[i] : number = '';
немного неправильный синтаксис, и тебе же не нужно обнулять строку каждый раз

2023-06-15 10:01 UTC, yartseva-ksenia commented on js/functions.js
> +    const NumberIsNan===true ? number += string[i] : number = '';
Дада, я с этой функцией помучалась. Теперь все ок)

2023-06-15 19:40 UTC, baileys-li commented on js/functions.js
> +    number = NumberIsNan === true ? number : number + string[i];
Я бы посетовал тут нейминг (с большой буквы обычно называют Классы и Енамы, но не переменные)
И переменная и так булевая
```suggestion
    const characterIsNan = Number.isNaN(parseInt(string[i],10));
    number = characterIsNan ? number : number + string[i];
```

2023-06-15 19:42 UTC, baileys-li commented on js/functions.js
> +  return Number(parseInt(number,10));
Излишне, parseInt возвращает и number
```suggestion
  return parseInt(number,10);
```

2023-06-16 05:44 UTC, yartseva-ksenia commented on js/functions.js
> +    number = NumberIsNan === true ? number : number + string[i];
ой, точно! Поправила

2023-06-16 05:45 UTC, yartseva-ksenia commented on js/functions.js
> +  return Number(parseInt(number,10));
Исправила

2023-06-16 16:32 UTC, merged