Открывается и закрывается
htmlacademy-javascript/1938675-kekstagram-29 pull request #7
Opened 2023-07-06 11:23 UTC by yartseva-ksenia

Сначала все шло неплохо - функции для откр/закр большой картинки написала сама, а на задаче "связать данные из миниатюр с большими фото" посыпалась((
Смотрела прошлый созвон - добавила обработчик в цикл, а потом написала функцию onPictureClick. Но, насколько я поняла из созвона - должно быть что-то одно. В любом случае - не пойму, что дальше делать...как эти данные передать в openBigPhoto для отрисовки в попапе.
Подскажи, куда смотреть, плиз!

2023-07-07 10:11 UTC, baileys-li requested changes
Запуталась в деструктуризации. Дальше сама

2023-07-07 10:11 UTC, baileys-li commented on js/full-photo.js
> +  //pictureDescriptionElement.alt = description;
```suggestion
const openBigPicture = ({url, description, likes, comments}) => {
  pictureWrapper.classList.remove('hidden');
  document.body.classList.add('modal-open');
  socialCommentCount.classList.add('hidden');
  commentsLoader.classList.add('hidden');

  pictureImgElement.src = url;
  commentsCountElement.textContent = comments;
  likesCountElement.textContent = likes;
  pictureDescriptionElement.alt = description;
```

2023-07-07 10:11 UTC, baileys-li commented on js/render-pictures.js
> +};
Давай пока будем замыкать
```suggestion
```

2023-07-07 10:11 UTC, baileys-li commented on js/render-pictures.js
>  });
```suggestion
const createPictureMarkUp = ({id, description, comments, likes, url}) => {
  const pictureElement = pictureTemplate.cloneNode(true);
  const imageElement = pictureElement.querySelector('.picture__img');
  imageElement.src = url;
  imageElement.alt = description;

  pictureElement.dataset.id = id;
  pictureElement.addEventListener('click', onPictureClick);

  pictureElement.querySelector('.picture__comments').textContent = comments.length;
  pictureElement.querySelector('.picture__likes').textContent = likes;

  return pictureElement;
};

const renderPicture = ((photo) => {
  const pictureElement = createPictureMarkUp(photo);

  pictureElement.addEventListener('click', (evt) => {
    evt.preventDefault();
    openBigPicture(photo);
  });

  pictureListFragment.appendChild(pictureElement);
});
```

2023-07-10 09:17 UTC, yartseva-ksenia commented on js/render-pictures.js
>  });
Вроде разобралась) Работает)

2023-07-10 09:17 UTC, yartseva-ksenia commented on js/render-pictures.js
> +};
ок, убрала это

2023-07-10 12:56 UTC, merged