Открывается и закрывается (часть 2)
htmlacademy-javascript/1938675-kekstagram-29 pull request #8
Opened 2023-07-12 09:51 UTC by yartseva-ksenia

Где-то я опять запуталась.
Посмотрела встречу, попыталась воспроизвести что-то подобное, не подглядывая, но следуя твоему ходу мыслей.
Сейчас все почти работает, только когда закрываю одно фото и открываю следующее — счетчики не сбрасываются, а продолжают прибавляться...не могу понять, где и что нужно исправить

2023-07-12 14:36 UTC, yartseva-ksenia commented
Я понимаю, что, скорее всего, чтобы сбросить счетчик - нужно удалять слушатель, но при добавлении строки commentsLoader.removeEventListener('click', onLoadMoreClick); в функцию clearComments — решить вопрос не получается

2023-07-12 17:23 UTC, baileys-li requested changes

2023-07-12 17:23 UTC, baileys-li commented on js/comments.js
> +};
Лучше её вынести в утилиты и использовать для миниатюр фото. Тут просто очень общая логика, которая применима не только к коментам

2023-07-12 17:23 UTC, baileys-li commented on js/comments.js
> +  });
1. Смотри ты подписываешь сюда анонимную функцию. Ты не сможешь её потом отписать, потому что у неё нет имени
```suggestion
  commentsLoader.addEventListener('click',onLoadMoreClick);
```

2023-07-12 17:23 UTC, baileys-li commented on js/comments.js
> +};
2. Теперь мы можем попытаться её отписать
```suggestion
const clearComments = () => {
  commentsList.innerHTML = '';
  commentsLoader.removeEventListener('click',onLoadMoreClick);
};
```

2023-07-12 17:23 UTC, baileys-li commented on js/comments.js
> +const onLoadMoreClick = (comments) => {
3. Но обработчик событие принимает только событие, поэтому нам нужно на верхнем уровне обозначить что такая функция будет

```suggestion
let onLoadMoreClick = null;
const createSliceRenderer = (comments)  = () => {
```

2023-07-12 17:23 UTC, baileys-li commented on js/comments.js
> +  onLoadMoreClick(comments);
5. 
```suggestion
  const renderCommentSlice = createSliceRenderer(comments);
  onLoadMoreClick = renderCommentSlice;
```

2023-07-12 17:50 UTC, yartseva-ksenia commented on js/comments.js
> +const onLoadMoreClick = (comments) => {
Да, я понимала, что как0то нужно по ссылке обработчик передавать, чтобы потом его отписать. Но не смогла сообразить, как это)
Меня смущает конструкция `(comments)  = () => {` . Это опечатка, наверное - должно быть так `(comments) => {` ?

2023-07-12 17:52 UTC, yartseva-ksenia commented on js/comments.js
> +  onLoadMoreClick(comments);
Если я убираю `commentsList.innerHTML = '';`, то при первом открытии картинки - остаются 2 рыбных коммента...потому что функция clearComments срабатывает только при закрытии окна большой картинки.

2023-07-12 18:08 UTC, baileys-li commented on js/comments.js
> +  onLoadMoreClick(comments);
А, окей.

2023-07-12 18:15 UTC, yartseva-ksenia commented on js/comments.js
> +};
Это странно, но, когда я переношу эту функцию в утилиты - перестают отрисовываться миниатюры, хотя я модуль с миниатюрами вообще никак не трогала

2023-07-12 18:18 UTC, yartseva-ksenia commented
Внесла правки и загрузка комментов пачками совсем сломалась) Клик на кнопку не срабатывает почему-то...

2023-07-12 18:28 UTC, baileys-li commented on js/comments.js
> +const onLoadMoreClick = (comments) => {
Писал на скорую руку. Поправил. Тут смысл в том, что функция возвращает функцию

2023-07-13 05:21 UTC, yartseva-ksenia commented on js/comments.js
> +};
этот вопрос решила - забыла расширение у util.js прописать в импорте)

2023-07-13 08:49 UTC, baileys-li requested changes

2023-07-13 08:49 UTC, baileys-li commented on js/comments.js
> +const createSliceRenderer = (comments) => {
Тоже самое что писал в прошлый раз
```suggestion
const createSliceRenderer = (comments) => () => {
```

2023-07-13 08:49 UTC, baileys-li commented on js/comments.js
> +};
чистим все стейты
```suggestion
const clearComments = () => {
  shownComments = 0;
  commentsLoader.removeEventListener('click', onLoadMoreClick);
};
```

2023-07-13 08:49 UTC, baileys-li commented on js/comments.js
> +  onLoadMoreClick = renderCommentSlice;
Делаем первый рендер
```suggestion
  const renderCommentSlice = createSliceRenderer(comments);
  renderCommentSlice();
  onLoadMoreClick = renderCommentSlice;
```

2023-07-13 10:13 UTC, yartseva-ksenia commented
Вместо const 
```
const renderCommentSlice = createSliceRenderer(comments);
renderCommentSlice();
onLoadMoreClick = renderCommentSlice;
```

показалось логичным написать так, ибо зачем создавать новую переменную и присваивать ее onLoadMoreClick, если можно сразу createSliceRenderer(comments); для onLoadMoreClick присвоить. Вроде все работает правильно)
```
onLoadMoreClick = createSliceRenderer(comments);
onLoadMoreClick ();
```

2023-07-13 12:50 UTC, merged